Add method to get username by user id
TouchInstinct/Backend-common pull request #33
Opened 2021-07-05 16:29 UTC by yasnovmi

2021-07-05 16:46 UTC, abuntakov requested changes

2021-07-05 16:46 UTC, abuntakov commented on auth-core/src/main/kotlin/ru/touchin/auth/core/user/services/UserCoreService.kt
> +    fun getOrNull(id: UUID): UserAccount?
`getUserAccountOrNull` так как возвращается не `User`

2021-07-05 16:51 UTC, yasnovmi commented on auth-core/src/main/kotlin/ru/touchin/auth/core/user/services/UserCoreService.kt
> +    fun getOrNull(id: UUID): UserAccount?
\+

2021-07-06 11:07 UTC, abuntakov approved these changes

2021-07-06 11:11 UTC, merged