Add logout and password update methods
TouchInstinct/Backend-common pull request #34
Opened 2021-07-08 15:02 UTC by yasnovmi

2021-07-08 15:16 UTC, abuntakov requested changes

2021-07-08 15:16 UTC, abuntakov commented on auth-core/src/main/kotlin/ru/touchin/auth/core/user/services/UserCoreServiceImpl.kt
> +                devices = hashSetOf()
а зачем? разве юзер не может быть залогигненым на другом устройстве?
Надо на это тест добавить:
- юзер логиниться на разных устройствах, разлогинивается на одном. На втором должен быть залогиненым.

Возможно надо метод логина/регистрации поправить. При логине/регистрации у юзера не обнулять устройства, а добавлять новые

2021-07-08 20:04 UTC, yasnovmi commented on auth-core/src/main/kotlin/ru/touchin/auth/core/user/services/UserCoreServiceImpl.kt
> +                devices = hashSetOf()
\+

2021-07-15 09:49 UTC, abuntakov approved these changes

2021-07-15 10:23 UTC, merged