Add HPK Android-related DTO's
TouchInstinct/Backend-common pull request #89
Opened 2022-11-02 13:42 UTC by Korna

2022-11-02 13:47 UTC, abuntakov requested changes

2022-11-02 13:47 UTC, abuntakov commented on push-message-provider-hpk/src/main/kotlin/ru/touchin/push/message/provider/hpk/clients/hms_hpk/dto/android/AndroidButton.kt
> +                    require(data.length < 1024) { "Data length cannot exceed 1024 chars" }
magic numbers. Откуда такое требование7 надо через пропертя задавать

2022-11-02 13:56 UTC, Korna commented on push-message-provider-hpk/src/main/kotlin/ru/touchin/push/message/provider/hpk/clients/hms_hpk/dto/android/AndroidButton.kt
> +                    require(data.length < 1024) { "Data length cannot exceed 1024 chars" }
Условия проверки входных данных взяты из репозитория с [примерами](https://github.com/HMS-Core/hms-push-serverdemo-java) реализации API к HPK и дополнены условиями из [документации](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/https-send-api-0000001050986197)

2022-11-07 14:14 UTC, abuntakov approved these changes

2022-11-07 14:14 UTC, merged